### ISSUE TITLE
bug: Code gives exception on workflows

### ISSUE THREAD

**Issue by anzelpwj** [copier-org/autopretty#13] opened 2021-04-25 21:36 UTC
**Describe the problem**

I tried following the instructions in the readme, and got the following error:

```
Create configurations specific to GitHub?
This includes a workflow to check code, issue and PR templates...
github? Format: bool
🎤? [Y/n] n

    create  .flake8
    create  .copier-answers.autopretty.yml
    create  .editorconfig
    create  .prettierrc.yml
    create  .gitignore
    create  .pre-commit-config.yaml
Something went wrong. Removing destination folder.
Traceback (most recent call last):
  File "/Users/homedir/anaconda3/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/plumbum/cli/application.py", line 614, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/plumbum/cli/application.py", line 609, in run
    retcode = inst.main(*tailargs)
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/copier/cli.py", line 38, in _wrapper
    return method(*args, **kwargs)
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/copier/cli.py", line 252, in main
    self.parent._copy(template_src, destination_path)
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/copier/cli.py", line 187, in _copy
    **kwargs,
  File "/Users/homediranaconda3/lib/python3.6/site-packages/copier/main.py", line 147, in copy
    copy_local(conf=conf)
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/copier/main.py", line 196, in copy_local
    render_folder(rel_folder, conf)
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/copier/main.py", line 371, in render_folder
    make_folder(dst_path)
  File "/Users/homedir/anaconda3/lib/python3.6/site-packages/copier/tools.py", line 91, in make_folder
    os.makedirs(str(folder))
  File "/Users/homedir/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workflows'
```
my repo is then completely deleted. Is `/workflows` supposed to be `./workflows`?

**Template**

This `autopretty` template

**To Reproduce**

1. Run `copier ...`
2. Answer ...
3. Choose ...

**Expected behavior**

Successfully create template.

**Screenshots/screencasts**

See above code block.

**Environment**
 - OS: Mac OSX 10.14.6
 - Copier version: copier 5.1.0
 - Python version: Python 3.6.7 |Anaconda
 - Installation method: pip

**Additional context**

None

**Comment by anzelpwj** [comment] 2021-04-25 21:37
(FWIW I replaced my username with `homedir` since I'm working on a work laptop).

**Comment by yajo** [comment] 2021-04-26 07:22
Duplicate of https://github.com/copier-org/copier/issues/285. Will be fixed in copier v6.

**Closed as completed by yajo** 2021-04-26 07:22 UTC
Labels: bug
